#+TITLE: 财富自由革命之路(八)
#+DATE: 2025-12-28
#+DRAFT: false 
#+AUTHOR: Valueote
#+CATEGORIES[]: 财富自由革命之路



* 财富自由与危机意识

大家好，今天是我们第四到五周的课程了其实在课表上。这一周我们主要讲的是标题叫做90后新时代。在正式讲课之前呢先讲几个比较好玩的事情。
第一个有的粉丝呢说就是我经常讲节目的时候说是孙总，说感觉跟我有距离感啊。其实我觉得是大家不了解我们这个事情的语境。

我们整个公司其实从来没有人叫过我孙总。为什么我特别喜欢用孙总这个词做自嘲呢？就是因为我们整个公司都没有任何人叫我孙总。
但是相反很多就是跟我根本就不熟的人见了我, 老叫孙总孙总。所以就是我们公司除了其实外面的人进来之外其实没有人会叫我孙总。
我经常在节目里面讲孙总其实是一种自嘲，其实除了孙总自己叫自己为孙总之外，没有人叫我为孙总，所以其实这某种程度上是一个梗。

然后我讲一下就因为我们大家其实前面课程大家也听了，我们当近52周的课程的。所以这个课程本身呢是个非常长的课程，
所以我觉得大家希望大家有耐心，一起来陪我一起把这个财富自由之路这个课程讲完。因为其实从我自己的角度来说呢，其实我是想随着大家啊，
其实这一年其实不光是教大家财富自由，也是把我自己关于财富对于世界的理解，包括怎么样迅速实现一个人个人和国家甚至的提升，
我自己的政见，还有很多我自己真实的想，法都写入到这个节目里面了。所以我是一个非常想跟大家有一种灵魂上的交流啊，
真正把我的世界观全盘托出，把我今后对未来的预测吧很多想法都注入到这个节目里面。所以它可能要比一开始很多人购买时想的我觉得要深度首先要深的多，
也更宏大的多，而且我觉得你得到的东西也会更多。

这个可能跟我们一开始就是节目里面有些文案我觉得是不相符的。因为文案呢当时跟小编商量的时候，他们为了提高销售转化啊什么的，
可能把我们的这个课程写的也跟比如说刘一秒啊陈安之啊，要你成功请成功，你不成功好像明天陈安之就把你们家门踹掉然后就冲进来，
把你拉出去让你成功一样，写写好像是这种文案。但实际上其实我们是一个我觉得更为深刻和更有深度，以及非常的有凝聚力的一个社群吧。
就像其实今天我录制这期节目的时候，川普刚刚当选美国总统。其实我本人当然其实大家前面如果有人就是听过我在群里互动的时候，
我也讲过川普本身是个很成功的商人，所以我当然是非常看好他的。我觉得他成为美国总统，不管对中国如何啊，但是对美国一定是一件好事，
他一定能带领至少美国这个国家走上一个非常实用主义的非常正确的道路。而川普为什么能选上总统呢，我觉得川普与有铁杆称他的粉丝是密不可分的。

而川普其实我不知道大家了不了解啊，就是川普能当上总统呢这个很重要的原因就是川普的粉丝支持川普的强度要远远比希拉里的粉丝支持她要强。
也就是从这个角度来讲川普这边是众志成城之师，希拉里那边是乌合之众，我觉得真的是这样。所以价值观给人带来的凝聚和真正给人带来的这种，
包括对事业改变的这个可能性和强度啊，都远远被大家低估了。真的是远远被大家低估了。甚至包括我当时逆转考上北大，
其实我前段时间我跟我们员工在聊天，大家也经常说我是这个Miracle Maker，奇迹制造者。

为什么屡屡能够在大家认为我根本干不成的事情上迅速干成，我觉得跟价值观最后给我的力量是密不可分的。
而这一点恰恰是最容易被大家忽略的。尤其是中国人这么多年我觉得长期沉浸在一种病态的实用主义中，非常轻视精神的力量，
说物质物质才是实的，给我讲天天的虚的，给我讲实的。其实我觉得某种程度上真的是很忽略精神的力量。
我们这个节目最后我会给大家讲精神和价值观的力量以及指引的力量，所以希望大家耐心的听下去。
我们这个每一集会把这个事情娓娓道来的。

所以呢，这个4到5周90后新时代其实又是一期虚的节目。但是我们打算坚持把虚的节目讲下去。虚的节目我们以后这样，
为了让大家呢满足大家一部分需求，到时我们虚实交叉吧。但其实这也是不好的，虚实交叉打乱了课纲。
因为我个人认为这样讲是最好的，其实就按照课纲来说啊。就比如说，爱因斯坦教你学天体物理，你不能说那牛顿第一第二定律是吧，
爱因斯坦相对论这基本定律都别讲，先教教我怎么算微积分，明天我妈叫我卖菜的时候画个曲线了。这个你就不是学习的态度哥们。
所以我们讲的就是其实按照课纲是这样啊，如果大家实在要求要加干货，我们可以往前拉，
就像我们之前好像把一个在30多周要讲的内容提到前面来讲了吧。其实而且我觉得大家如果呢不是太理解道的话，
后面的术啊也很难真正透彻的理解。

所以今天这个还是在讲道，90后新时代。我先讲讲为什么起这个标题吧，然后再讲就是我们后面要讲的内容。要起这个标题呢，
我的一个主要原因是因为呢，我个人认为中国在未来的，现在今年是2016年，到2036年，2040年，我们中国我觉得这20多年呢，
我们中国将进入一个我觉得是与危机并存的时代，一个新时代。但是我觉得与前面的情况来说我更愿意称它视为一种新的危机，
而并某种程度上不是一个新的机遇。是因为中国人前30年的情况过得都太好，我觉得如果说我们这个与前面这30年, 就尤其可能从78年开始算，
包括从92南巡开始算，这二三十年中国都做得是非常好的，整体的整个社会增长是非常迅速的。所以大家呢其实社会社会阶层之间也不容易出现撕裂，
因为蛋糕都是一直在做大嘛。但是未来的20多年啊，我觉得是整个国家及社会会面临新的危机。

所以90后啊，为什么叫90后新时代。就90后这一代人也是中国第一代在成年路上将目睹中国经济滞胀甚至下滑的一代人。
其实你看现在啊，现在40后都已经70多，大家想一下40年出生的人现在已经76岁了。也就是说绝大多数哪怕是共和国的同龄人, 我们父辈那一代，
像我们爷爷那一辈很多人都去世了是吧，包括我爷爷都去世了。像我们就是基本上我们上面只有一代了嘛，就我父母那一代。
他们这一代人其实基本上已经都是改革红利的见证者了。所以即便对于我父母这一代人我觉得还是很幸运的，
因为他们基本上绝大多数的成年时代已经生活在中国高速增长的年代里了。而90后00后就不用说了，以后的10后，
我们主要的生活的时代将是中国一个新危机的时代，个人认为。所以这就是为什么叫中国90后新时代的一个主要原因。

所以这个是为什么我觉得就是今天在听我们节目的这个读者啊听众，我觉得不管你是几零后了，其实你如果再在今天再听这个节目，
我相信你现在已经处于自己年华中最宝贵的这一段时间。我觉得我们还是要有一种非常强的责任感与自豪感的。
首先是中国能不能安然的度过这一场危机以及度过紧接下来的各种问题，其实非常有赖于我们这一代人的付出以及努力, 
以及对这个危机的预判和准备。其次呢你自己当然也能够从对这个危机的准备和预判中得到好处。
这个好处就是危机来的时候你至少不会受到危机的影响，或者你至少是在这个社会中承担主要增长力量的那部分人，
而你不会因为大时代的洪流来袭的时候把你给卷走了。你是在岸上去救别人的人，而不是在洪流被卷走时候在下面哀嚎等别人救的人。
你会是诺亚方舟上最后被救上来的那些，要保存到人类灭亡之后的新物种，而不是上帝选择洪流来要被消灭的那一群人。

所以从这个角度来讲，我觉得大家还是要有一个非常强的自觉性，自觉感，甚至有点像犹太人，
觉得自己我就是上帝的选民啊，我就是上帝选民，这个上帝就给我们投票选出来的，是吧，有这种感觉。
我觉得对于中国啊包括社会啊未来面对的新的危机，这种其实国家的危机往小里说是家庭的危机是吧，也是个人的危机，
你对这个事情的提前判断准备，都将会在未来2到30年对你对你的家庭, 甚至对你周边的社会乃至这个国家产生很深远的影响。

所以不要以为不要以为这我们经常讲的好像利己主义个人主义只是为了自己，不是的。我们把自己做好了，
把自己作为做成了一个发光发热的光源，那这个国家就更有希望，这个社会就更有希望。就更不容易在危机中最后变成一盘散沙，
最后甚至完蛋。所以这个当然是非常重要的。所以我觉得其实我们经常讲的所谓的个人奋斗个人独立，其实真正意义上是具有非常大的国家和社会意义了。
因为我们把这些事情做好之后，如果这一群人的群体足够多，人足够广泛，那就会在危机来临的时候对这个国家产生非常大的影响。
这就是经常我们如果大家读过圣经，对所多玛的义人啊是不是啊。哪怕那个所多玛那城市整体烂掉了，但是这所多玛里面有几个好人有几个牛逼的，
说不定上帝因为他们这个城市就不动了呀，说不定因为他们这个整个国家就能安然度过这场危机。
所以从这个角度来讲我觉得大家是一定要有，有一种甚至代表人类奋斗的这种崇高感。我觉得真的是这样。

* 性与权力


那大家会问了，那你这说二三十年，二三十年的这个主要危机是啥危机呢？要来的这个什么危机呢？我们讲一讲，一共有以下好几个危机。

第一个危机大家不用说了，就是中国经济本身内源性结构的危机。讲起来很简单，就是中国的经济增长了这么多年，
总该滞胀、总该负增长了吧？这是很正常的。这个我觉得大家是毋庸置疑的，因为你去看美国、日本这些发达国家的增长曲线，
中国GDP、人均GDP到达一个门槛之后，自然而然要往下走。这就跟人的生老病死一样，是再正常不过的了。
所以从这个角度来讲呢，中国本身经济大环境将进入一个长期滞胀，或者是长期的低增长，乃至负增长。这个是我觉得所有中国人，
现在中国的成年人，都必须去深刻认识和体悟的一个大前提。

这会对你的人生有非常大的影响的呀。你想想以前我们整个改革开放30年、40年，是生活在一个多么昂扬的乐观主义的情绪里面的。
现在有多乐观，其实未来的情况可能就有多糟。这个其实是所有人都必须注意的，就是甚至你回头想想，如果我和我的子女、我的父母，
未来都将生活在一个经济长期低增长、滞胀的国家，缺乏经济新增长点的一个国家，与机会的这么一个态势下，
我们将如何去配置我们的财产？我们将如何去自处我们的人生呢？其实这是本来就是一个非常值得去深刻思考的话题。
我觉得这是第一个问题。

第二个问题呢，就是整体的产业结构，中国也会发生非常大的变化。大家也知道，就是我们中国的整体产业结构呢，
以前还是以工业、房地产，以及工业和房地产背后所拉动的一系列的行业，作为主要经济增长点的。
当然还包括外贸，作为一个非常主要经济增长点的。而现在这些产业结构随着中国的经济危机，也随着这些产业结构本身所具有的，
我们经常叫短暂时性也好啦，叫它阶段性也好啦，它本身具有这些东西。

这个其实我觉得大家不用看美国、日本，光看看韩国跟台湾就很明显了，这些基本上就是我们前一段时间，
比我们大概领先个一二十年的产业形态和状态。像当年在日韩、台湾的产业，西方转移到中国，现在转移完到中国，
现在很快会转移到像越南和印度这些地方去。所以包括大家今天不要笑，川普的支持者，包括很多美国的，像那些汽车工人，
这些从事工业的、大量的产业工人，因为产业结构升级转型，都将走向下岗。
那美国就不叫下岗了，叫失业，或者他的人生会面临很多问题。再加上社保、养老金，这些我相信还不用等到我们用，
基本到我们父母用的时候，我觉得都会出事的。所以这时候你都要想想，这些事情一股脑就全部都过来了。

产业结构转型所带来的产业结构，那当然不用说了，基本上不是人下岗的问题，是一个一个产业成批量的被拔掉。
然后同时，可能社会的Safety Net，我们讲的社保养老金，这些都会出问题，这很正常。
大家也知道现在就开始出问题了，否则为什么延迟退休呢？这些产业结构全部都会出问题。所以大家也不要笑，
今天台湾、美国出现了很多问题，其实在中国都会原封不动的来一遍，我觉得太正常了，太正常了。

所以，这也让90后适应社会产生的大困难。因为比如不说光90后，其实所有人面对这个问题。
举个例子，你70后、80后难道不面临这个问题吗？绝大多数人在大学，包括高中、初中接受教育的时候，
他所接受的这一整套教育是工业体系下的这一整套教育。举个例子，我们公司一位员工学社会工作，
这些都是典型的工业化时代下的产物。包括我北大太多同学学化工的吧，学各式各样工业时代生产所产生的，是吧。
包括还有那些学石油的，学这些的，工业时代下的这一整套玩意儿的。然后包括我们很多文科生学文学，学历史的，
那都是工业时代下的产物。包括我大量同学现在还在传统媒体工作啊，对吧。在新闻、纸媒，这些都是将来会被革命的，
在党报啦，在各式各样的党报，你现在连党报都要求要搞双微了，是这道理吧。

所有的建立在这一整套工业体系下的行业都会发生个翻天覆地的转型。就包括前一段时间在微信群很多同学问我，
就说，哎，孙总, 我干这个，说去互联网，我靠，我一没读过互联网，二大学学的是石油化工，咋整呢？
现在好像去石油化工薪水也很低。这个就是我们刚才讲的产业结构转型中具体体现。
产业结构转型不是一个孙总跟你讲的一个好像很天花乱坠的, 一个编的新词蒙你呢。

它是有非常具体的适应症以及投射形态的，投射形态投射到你身上就是个问题啊。你说我以前学的这个去互联网没有经验，
这就是一个非常结构的产业转型问题。不光你会遇到，这整个社会整个国家都会遇到，而且这都是个非常大的挑战。
那对于一个国家主席、省委书记，美国总统都是很大的挑战，更何况你呢。但是好消息是你个人解决起来可比国家解决起来容易得多得多，
所以这个也让90后产生很大的困难。

第三，然后我呢把这两个总结一下，总结出了第三个。第三个呢，当然我就觉得既是危机也是机会，也是人类的一个新进步，
所以为什么叫标题是90后新时代呢。就是我总结了一下，中国未来的新危机也好，新机会也好呢，
本质就是传统社会、工业时代下传统社会将面临最后一次转型。转型怎么转呢？叫做从家庭为单位的工业生产社会，
向个人为单位的互联网社会的转型和变化。

所以我们将来，我再念一遍，我们将来的所有问题都建立在这个上面：从家庭为单位的工业生产社会，
向个人为单位的互联网社会的转型和变化。

首先大家要注意，一是之前以家庭为单位，后面咱们是以个人为单位。其次咱们原来是个工业生产社会，转变的目的是叫互联网社会。
大家要注意，这是未来人类，甚至我觉得不光是我们国家，全球的发达国家都要面临这个转型。甚至不光你现在听到你可能明白了，
有的国家元首听的都不明白了。你像德国整体还是搞工业4.0的，不搞所谓的互联网。我觉得在互联网领域，如果不做的国家，
整体国家会落后，社群会落后，民族会落后，个人当然也会落后，这是毫无疑问的。所以为什么我经常说讲战略讲战略讲战略，
这个话说一百遍都不会过了。如果战略扑了个空，那基本上是国家民族社会个人集体踏空，不会有例外的。

所以这是为什么我现在一点都不建议很多人问我说能不能去国外读书，要不要移民，我都不建议。我觉得在中国很好，
中国和美国可能是两个唯一非常注重互联网的这个民族，他们对这个问题看得非常深刻。我觉得它会被命运所奖励的。

所以从这个角度来说，从家庭为单位的工业社会生产社会，向个人为单位的互联网社会的变化，是未来整个我觉得未来三四十，
甚至五十一百年的变化的主旋律。人类会从家庭为单位的工业生产社会，不断向个人为单位的互联网社会去变化。
如果这个变化要花一百年，咱就花一百年，如果五十年就花五十年，就这么简单。这是个未来大的趋势。

以前呢，王尔德说过一句话，我非常欣赏，是总结以前我们的社会的，就是以前可能非互联网社会的时候的一句话。
跟大家分享一下，英文叫：Everything in the world is about sex, except sex. Sex is about power. 这句话大家在纸牌屋，
Frank Underwood也说过这句话。

翻译成中文叫什么呢？就是说这个世界上的万事万物，都是关于性与繁殖的。只有一件事不是关于性与繁殖的，就是性本身和繁殖本身。
因为繁殖和性本身是关于权力的。

这句话可能对于我们很多听众都很深奥，我可以给大家做一个解释。首先呢，为什么说叫万事万物都是关于繁殖和性的，
其实我觉得这个大家是太容易理解了。就是我们以家庭为单位的传统工业生产社会，
基本上和我们以前以家庭为单位的农业生产社会一样，永远都是关于性和繁殖的。

大家想想，我们每个人，我们基本上人生路线全部都是，无论你长到什么时候，
到达一个适婚年龄就必须赶紧结婚吧。然后你结婚之后，你就必须生小孩吧。你生小孩你就必须把这小孩好好养吧。
然后你养这个小孩的时候，就会出现各种各样的遗产问题，养这个小孩，对哪个小孩亲切，教育资源什么，全部都是关于性与繁殖的。
你后来想想你人生中做的每一步，赚的所有钱，准备的所有机会，难道不都是为性与繁殖这件事在服务吗？甚至你想一想，
甚至不光咱们别说人了，咱们整个人都是为性与繁殖在服务。就你一辈子所有事就围绕着这个东西打转了，
尤其对于普通人来说更是这样。就一辈子，你看，你就为了自己的小孩，为了自己的父母，为了自己的家庭，永远打转的，
就是性与繁殖本质上。你就是为了这个事存在的。

其实你想想国家又不是如此吗？以前，以封建社会，就在家庭为单位的农业社会生产的时候，那你给我们国家耗荡两三千年历史。
首先权力的分配永远都不是通过你的能力来分配，都是嫡长子继承制啊。谁就是因为皇帝睡了他的正牌老婆生的小孩，
拥有最先的权力继承权。所以基本上你可以看，即便国家的资源分配，权力分配，一切的分配，咱们本质是一种性分配。
所以这就叫为什么是以家庭为单位。然后去协调，哪怕农业生产、工业生产都是这样的。所以这叫王尔德为什么说，
everything in the world is about sex.

但是为什么 except sex呢？繁殖本身是关于什么？就是以前家庭为单位的工业生产社会的本源，就叫做权力。繁殖是关于权力的。
大家说这句话又怎么理解呢？太好理解了， 首先以我前面已经举的例子了，你看，繁殖关系权力。一个国家到底谁来管？
谁说了算？基本上是跟他的性有非常强的关系的。比如说我是皇后的儿子，那就该我管，对吧？你是妾的儿子，那就不归你管。
小到一个家庭，我前一段时间才去了我们山东老家，看了我们祖谱，都是这样的。首先女性是没有家族继承权的。
女性是不能进家谱的。我们在家谱里面孙氏家谱，记了无数人，女的就是女生，姓孙的女的一个都没有。
  这就是非常明显的性和权力的关系。你如果是女性，连家谱都进不了。然后这就是所谓的sex is about power。

然后类似的例子太多了。我们决定一个社会，一个阶层，一群人，一个民族由谁来主宰？永远是通过性。
我们不会问说你是不是对这个家族贡献更大？你是不是表现很不错？甚至跟能力都没有关系，完全跟性。权力跟性是完全挂钩的。
所以从这个角度来讲，我觉得王尔德这句话，基本是把以家庭为单位的工业生产社会讲的是淋漓尽致。
